# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  # 配置thymeleaf相关信息
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.100.50
    port: 6379
# 配置feign的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  sentinel:
    enabled: true

logging:
  file:
    name: E://newcode/gmall-parent/service/logs/web-all